"""empty message

Revision ID: 7b4f253fbd11
Revises: 3bfd5eb2e4ff
Create Date: 2020-04-14 09:08:04.665827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b4f253fbd11'
down_revision = '3bfd5eb2e4ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('expense', sa.Boolean(), nullable=True))
    op.get_bind().execute("UPDATE items SET expense=TRUE; ")
    op.get_bind().execute("UPDATE items SET expense=FALSE WHERE category_id = 3; ")
    op.get_bind().execute("ALTER TABLE items ALTER COLUMN expense SET NOT NULL;")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'expense')
    # ### end Alembic commands ###
